### PR TITLE
Circle radius size

### LINKED ISSUE #63: make adjustments to circle radius and/or filter by population size on state zoom
overall the circle radius could be a bit smaller, at both the US and the state zoom levels. But at the state zoom levels, some states are very crowded. Either filter out some of the smaller cities or reduce the radius when the map zoomed in, or both.

### PR DESCRIPTION
**Pull request by jacobdv**
I halved the circle radius when an individual state is selected. It's easy enough to adjust if that size doesn't feel quite right but it seemed like a good starting spot and allows more of the data to be seen.

### CODE REVIEW

**Comment by blackdotbug** [comment]
Jacob you've got merge conflicts with main. Can you resolve those or do you need my help?

**Comment by jacobdv** [comment]
I have it resolved. There were two issues, one was completely on my end, the other seems to have to do with a duplicate file structure which has an 'assets' folder instead of a 'static' folder. I removed that from my commit so it doesn't conflict but it seems like an issue that may crop up again later for someone else.

**Review by blackdotbug — APPROVED** [review]
excellent! thanks, @jacobdv

**Review by blackdotbug — APPROVED** [review]
caught a typo

**Pull request merged**
