### PR TITLE
working tooltips wrongly positioned

### LINKED ISSUE #61: add tooltips to scatterplot
hover on circles should display at least city name

### PR DESCRIPTION
**Pull request by blackdotbug**

### CODE REVIEW

**Comment by blackdotbug** [comment]
hey @pete6184 I've got some working tooltips on here, but they need some love re: positioning and style.

**Comment by pete6184** [comment]
Positioned and styled!

I'm also looking into adding commas and rounding the decimals to only 2 decimals to the tooltip to make it look a little cleaner.

**Comment by blackdotbug** [comment]
beautiful! try toLocaleString with the maximum fraction digits option. I'll hold the merge until you've got that part done.

**Comment by pete6184** [comment]
Done. Thanks for the tip!

**Comment by pete6184** [comment]
Done! Thanks for the tip

**Pull request merged**
