### PR TITLE
added app.py endpoint and created api.html template

### LINKED ISSUE #65: add api homepage
add instructions page for api, with explanation of endpoints and examples of return data structure.

### PR DESCRIPTION
**Pull request by pete6184**
I added the new endpoint and created the new html page. I will work on the page throughout the weekend.

Heather - Please review and let me know if I am on the right path. I will do more styling once I am confident that I am doing it correctly. Also, I am a little confused by the new route I created and how it is used. I added it but when I run the "python app.py" it errors out. What am I missing here?

### CODE REVIEW

**Comment by blackdotbug** [comment]
Hi Pete! I'm getting error about the order of the routes in app.py. Could you move the base api endpoint above the city and state endpoints in the code? That should fix it. The order of your routes matters, so generally you start with the simplest and move on to more complex urls in the same structure.

**Comment by pete6184** [comment]
Heather. That didn't seem to fix it. I tried moving it where you suggested (and then every other possible position) and I am still getting the same error message.

**Comment by blackdotbug** [comment]
i'll take a look

**Review by blackdotbug — CHANGES_REQUESTED** [review]
All this needs is an example of how to structure the url for each endpoint. Nice work @pete6184!

**Comment by pete6184** [comment]
The app.py file is working now!! I will add the endpoint url structure and push those changes up shortly.

**Comment by pete6184** [comment]
Ok. I added the url structure to the text and linked them to the endpoints. I also linked the images of the endpoint examples to the url.

**Comment by blackdotbug** [comment]
there's one more endpoint, though... you've got one that takes a variable of the state abbreviation and returns just the cities for that state.

**Comment by pete6184** [comment]
You got me stumped on this one. I have the 'http://127.0.0.1:5000/api/states/' endpoint that returns all 50 states.  There's also the 'http://127.0.0.1:5000/api/cities/' which is only returning the cities in Oregon since we have that set as the default. I do see that we can have 'http://127.0.0.1:5000/api/cities/< state >/'  which will return the cities for the specific state we enter. Do you want me to add that as well and explain that you need to enter the state abbreviation at the end to specify which state to lookup?  I can't seem to find an endpoint that returns all cities/states if that's a third one you are referring to.

**Comment by blackdotbug** [comment]
That is exactly what I'm looking for. You are teaching folks how to use your api and your api can return the city data for a specific state, you just need to tell them how to structure the url to get the state's data they want.

**Comment by blackdotbug** [comment]
And make sure when you are adding links you make them relative links. "http://127.0.0.1:5000" should not appear anywhere in your code.

**Comment by pete6184** [comment]
Ok, I understand what you're saying there, but do I still need 3 then? It seems like the 'http://127.0.0.1:5000/api/cities/' would be redundant with the 'http://127.0.0.1:5000/api/cities/OR/' endpoint. I'm thinking I should  just explain how to add the api/states for a list of all 50 states and then api/cities/<state> for the cities of each individual state.

**Comment by blackdotbug** [comment]
sounds like a good way to go to me @pete6184

**Comment by pete6184** [comment]
I think I have this good to go until we get the Heroku up and running. Once we get that going I will change the links to be relative and make sure everything is working correctly.

**Pull request merged**
